/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91_Char93UnauthenticatedRouteImport } from './routes/[_]/_unauthenticated'
import { Route as Char91_Char93UnauthenticatedSignupRouteImport } from './routes/[_]/_unauthenticated/signup'
import { Route as Char91_Char93UnauthenticatedLoginRouteImport } from './routes/[_]/_unauthenticated/login'
import { Route as Char91_Char93ApiAuthSplatRouteImport } from './routes/[_]/api/auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_Char93UnauthenticatedRoute =
  Char91_Char93UnauthenticatedRouteImport.update({
    id: '/_/_unauthenticated',
    path: '/_',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91_Char93UnauthenticatedSignupRoute =
  Char91_Char93UnauthenticatedSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => Char91_Char93UnauthenticatedRoute,
  } as any)
const Char91_Char93UnauthenticatedLoginRoute =
  Char91_Char93UnauthenticatedLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char91_Char93UnauthenticatedRoute,
  } as any)
const Char91_Char93ApiAuthSplatRoute =
  Char91_Char93ApiAuthSplatRouteImport.update({
    id: '/_/api/auth/$',
    path: '/_/api/auth/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/_': typeof Char91_Char93UnauthenticatedRouteWithChildren
  '/_/login': typeof Char91_Char93UnauthenticatedLoginRoute
  '/_/signup': typeof Char91_Char93UnauthenticatedSignupRoute
  '/_/api/auth/$': typeof Char91_Char93ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/_': typeof Char91_Char93UnauthenticatedRouteWithChildren
  '/_/login': typeof Char91_Char93UnauthenticatedLoginRoute
  '/_/signup': typeof Char91_Char93UnauthenticatedSignupRoute
  '/_/api/auth/$': typeof Char91_Char93ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_/_unauthenticated': typeof Char91_Char93UnauthenticatedRouteWithChildren
  '/_/_unauthenticated/login': typeof Char91_Char93UnauthenticatedLoginRoute
  '/_/_unauthenticated/signup': typeof Char91_Char93UnauthenticatedSignupRoute
  '/_/api/auth/$': typeof Char91_Char93ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/_' | '/_/login' | '/_/signup' | '/_/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/_' | '/_/login' | '/_/signup' | '/_/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_/_unauthenticated'
    | '/_/_unauthenticated/login'
    | '/_/_unauthenticated/signup'
    | '/_/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char91_Char93UnauthenticatedRoute: typeof Char91_Char93UnauthenticatedRouteWithChildren
  Char91_Char93ApiAuthSplatRoute: typeof Char91_Char93ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/_unauthenticated': {
      id: '/_/_unauthenticated'
      path: '/_'
      fullPath: '/_'
      preLoaderRoute: typeof Char91_Char93UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/_unauthenticated/signup': {
      id: '/_/_unauthenticated/signup'
      path: '/signup'
      fullPath: '/_/signup'
      preLoaderRoute: typeof Char91_Char93UnauthenticatedSignupRouteImport
      parentRoute: typeof Char91_Char93UnauthenticatedRoute
    }
    '/_/_unauthenticated/login': {
      id: '/_/_unauthenticated/login'
      path: '/login'
      fullPath: '/_/login'
      preLoaderRoute: typeof Char91_Char93UnauthenticatedLoginRouteImport
      parentRoute: typeof Char91_Char93UnauthenticatedRoute
    }
    '/_/api/auth/$': {
      id: '/_/api/auth/$'
      path: '/_/api/auth/$'
      fullPath: '/_/api/auth/$'
      preLoaderRoute: typeof Char91_Char93ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char91_Char93UnauthenticatedRouteChildren {
  Char91_Char93UnauthenticatedLoginRoute: typeof Char91_Char93UnauthenticatedLoginRoute
  Char91_Char93UnauthenticatedSignupRoute: typeof Char91_Char93UnauthenticatedSignupRoute
}

const Char91_Char93UnauthenticatedRouteChildren: Char91_Char93UnauthenticatedRouteChildren =
  {
    Char91_Char93UnauthenticatedLoginRoute:
      Char91_Char93UnauthenticatedLoginRoute,
    Char91_Char93UnauthenticatedSignupRoute:
      Char91_Char93UnauthenticatedSignupRoute,
  }

const Char91_Char93UnauthenticatedRouteWithChildren =
  Char91_Char93UnauthenticatedRoute._addFileChildren(
    Char91_Char93UnauthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char91_Char93UnauthenticatedRoute:
    Char91_Char93UnauthenticatedRouteWithChildren,
  Char91_Char93ApiAuthSplatRoute: Char91_Char93ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
