/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as UnauthenticatedChar91_Char93SignupRouteImport } from './routes/_unauthenticated/[_]/signup'
import { Route as UnauthenticatedChar91_Char93LoginRouteImport } from './routes/_unauthenticated/[_]/login'
import { Route as Char91_Char93ApiAuthSplatRouteImport } from './routes/[_]/api/auth.$'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const UnauthenticatedChar91_Char93SignupRoute =
  UnauthenticatedChar91_Char93SignupRouteImport.update({
    id: '/_/signup',
    path: '/_/signup',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedChar91_Char93LoginRoute =
  UnauthenticatedChar91_Char93LoginRouteImport.update({
    id: '/_/login',
    path: '/_/login',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const Char91_Char93ApiAuthSplatRoute =
  Char91_Char93ApiAuthSplatRouteImport.update({
    id: '/_/api/auth/$',
    path: '/_/api/auth/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/_/login': typeof UnauthenticatedChar91_Char93LoginRoute
  '/_/signup': typeof UnauthenticatedChar91_Char93SignupRoute
  '/_/api/auth/$': typeof Char91_Char93ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/_/login': typeof UnauthenticatedChar91_Char93LoginRoute
  '/_/signup': typeof UnauthenticatedChar91_Char93SignupRoute
  '/_/api/auth/$': typeof Char91_Char93ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_unauthenticated/_/login': typeof UnauthenticatedChar91_Char93LoginRoute
  '/_unauthenticated/_/signup': typeof UnauthenticatedChar91_Char93SignupRoute
  '/_/api/auth/$': typeof Char91_Char93ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/_/login' | '/_/signup' | '/_/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/_/login' | '/_/signup' | '/_/api/auth/$'
  id:
    | '__root__'
    | '/_main'
    | '/_unauthenticated'
    | '/_main/'
    | '/_unauthenticated/_/login'
    | '/_unauthenticated/_/signup'
    | '/_/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
  Char91_Char93ApiAuthSplatRoute: typeof Char91_Char93ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_unauthenticated/_/signup': {
      id: '/_unauthenticated/_/signup'
      path: '/_/signup'
      fullPath: '/_/signup'
      preLoaderRoute: typeof UnauthenticatedChar91_Char93SignupRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/_/login': {
      id: '/_unauthenticated/_/login'
      path: '/_/login'
      fullPath: '/_/login'
      preLoaderRoute: typeof UnauthenticatedChar91_Char93LoginRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_/api/auth/$': {
      id: '/_/api/auth/$'
      path: '/_/api/auth/$'
      fullPath: '/_/api/auth/$'
      preLoaderRoute: typeof Char91_Char93ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface UnauthenticatedRouteChildren {
  UnauthenticatedChar91_Char93LoginRoute: typeof UnauthenticatedChar91_Char93LoginRoute
  UnauthenticatedChar91_Char93SignupRoute: typeof UnauthenticatedChar91_Char93SignupRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedChar91_Char93LoginRoute:
    UnauthenticatedChar91_Char93LoginRoute,
  UnauthenticatedChar91_Char93SignupRoute:
    UnauthenticatedChar91_Char93SignupRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
  Char91_Char93ApiAuthSplatRoute: Char91_Char93ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
