/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91_Char93SignupRouteImport } from './routes/[_]/signup'
import { Route as Char91_Char93LoginRouteImport } from './routes/[_]/login'
import { Route as Char91_Char93ApiAuthSplatRouteImport } from './routes/[_]/api/auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_Char93SignupRoute = Char91_Char93SignupRouteImport.update({
  id: '/_/signup',
  path: '/_/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_Char93LoginRoute = Char91_Char93LoginRouteImport.update({
  id: '/_/login',
  path: '/_/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_Char93ApiAuthSplatRoute =
  Char91_Char93ApiAuthSplatRouteImport.update({
    id: '/_/api/auth/$',
    path: '/_/api/auth/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/_/login': typeof Char91_Char93LoginRoute
  '/_/signup': typeof Char91_Char93SignupRoute
  '/_/api/auth/$': typeof Char91_Char93ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/_/login': typeof Char91_Char93LoginRoute
  '/_/signup': typeof Char91_Char93SignupRoute
  '/_/api/auth/$': typeof Char91_Char93ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_/login': typeof Char91_Char93LoginRoute
  '/_/signup': typeof Char91_Char93SignupRoute
  '/_/api/auth/$': typeof Char91_Char93ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/_/login' | '/_/signup' | '/_/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/_/login' | '/_/signup' | '/_/api/auth/$'
  id: '__root__' | '/' | '/_/login' | '/_/signup' | '/_/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char91_Char93LoginRoute: typeof Char91_Char93LoginRoute
  Char91_Char93SignupRoute: typeof Char91_Char93SignupRoute
  Char91_Char93ApiAuthSplatRoute: typeof Char91_Char93ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/signup': {
      id: '/_/signup'
      path: '/_/signup'
      fullPath: '/_/signup'
      preLoaderRoute: typeof Char91_Char93SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/login': {
      id: '/_/login'
      path: '/_/login'
      fullPath: '/_/login'
      preLoaderRoute: typeof Char91_Char93LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/api/auth/$': {
      id: '/_/api/auth/$'
      path: '/_/api/auth/$'
      fullPath: '/_/api/auth/$'
      preLoaderRoute: typeof Char91_Char93ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char91_Char93LoginRoute: Char91_Char93LoginRoute,
  Char91_Char93SignupRoute: Char91_Char93SignupRoute,
  Char91_Char93ApiAuthSplatRoute: Char91_Char93ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
